# Generated by Django 6.0.2 on 2026-02-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.ForeignKey(help_text='Currency in which this budget limit is set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.currency'),
        ),
    ]
