# Generated by Django 6.0.2 on 2026-02-10 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_add_currency_to_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency in which this budget limit is set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.currency'),
        ),
    ]
