# Generated by Django 5.2.2 on 2026-09-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_budget_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_at_time',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate to USD at the time of transaction.', max_digits=12, null=True),
        ),
    ]
